import os


class Config:
    CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL')
    CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND')
    CELERY_TIMEZONE = 'UTC'
    CELERY_TASK_TIME_LIMIT = 86400
    CELERY_TASK_DEFAULT_RETRY_DELAY = 60
    CELERY_TASK_MAX_RETRIES = 3